kind: pipeline
type: docker
name: default

steps:
  - name: Check the code
    image: rust:1.63
    commands:
      - cargo check

  - name: publish website
    image: plugins/docker
    settings:
      registry: gitea.familleboyer.net
      username: traxys
      password:
        from_secret: docker_password
      repo: gitea.familleboyer.net/traxys/viz
      tags: latest
