kind: pipeline
type: docker
name: default

steps:
  - name: generating website
    image: gitea.familleboyer.net/traxys/viz-build:1.63
    commands:
      - apt-get update -y && apt-get install -y pandoc
      - cargo install trunk
      - cargo xtask build --release
