name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#web
    - run: nix profile install nixpkgs#minio-client
    - run: mc alias set loserver https://s3.familleboyer.net/ ${{ secrets.S3_ACCESS_KEY }} ${{ secrets.S3_SECRET_KEY }}
    - run: mc cp -r result/ loserver/viz-site
